server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:mem:address_book_data
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#enabling the H2 console
  h2:
    console:
      enabled: true
